import React, { createContext, useState, useEffect, useContext, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { publicApiClient, privateApiClient } from '../api/client';
import { AxiosError } from 'axios';
import { getStoredPushToken } from '../utils/pushNotifications';
import { registerPushToken, unregisterPushToken } from '../api/notificationService';
import { getPuanBalance } from '../api/puanService';

// Kullanıcı arayüzünü veritabanı şemasına göre düzenliyoruz
export interface User {
  id: number;
  name: string;
  username: string;
  email: string;
  role: 'user' | 'business';
  is_verified?: boolean;
  phone?: string;
  created_at?: string;
  favorite_business_ids?: number[];
}

interface LoginResponse {
  success: boolean;
  message?: string;
  needsUsernameSetup?: boolean;
}

interface AuthContextType {
  token: string | null;
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  needsUsernameSetup: boolean;
  puanBalance: number;
  refreshPuanBalance: () => Promise<void>;
  login: (username: string, password: string) => Promise<LoginResponse>;
  logout: () => void;
  setUser: (user: User | null) => void;
  signInWithGoogle: (googleToken: string) => Promise<LoginResponse>;
  signInWithApple: (appleToken: string, fullName: string | null) => Promise<LoginResponse>;
  completeUsernameSetup: (username: string) => Promise<{ success: boolean; message?: string }>;
  addFavorite: (businessId: number) => Promise<void>;
  removeFavorite: (businessId: number) => Promise<void>;
  isFavorite: (businessId: number) => boolean;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

// Kullanıcı adının otomatik üretilmiş olup olmadığını kontrol et
// Kullanıcı adının otomatik üretilmiş olup olmadığını kontrol et (backend fallback)
function isAutoGeneratedUsername(username: string): boolean {
  if (!username) return true;
  if (username.startsWith('google_')) return true;
  if (username.startsWith('apple_')) return true;
  if (username.startsWith('user_')) return true;
  return false;
}

export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const [token, setToken] = useState<string | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [needsUsernameSetup, setNeedsUsernameSetup] = useState(false);
  const [puanBalance, setPuanBalance] = useState<number>(0);

  useEffect(() => {
    const loadAuthData = async () => {
      try {
        const storedToken = await AsyncStorage.getItem('@authToken');
        const storedUser = await AsyncStorage.getItem('@authUser');
        if (storedToken && storedUser) {
          setToken(storedToken);
          const parsedUser = JSON.parse(storedUser);
          if (!parsedUser.favorite_business_ids) {
            parsedUser.favorite_business_ids = [];
          }
          setUser(parsedUser);
        }
      } catch (e) {
        console.error('Failed to load auth data from storage', e);
      } finally {
        setIsLoading(false);
      }
    };
    loadAuthData();
  }, []);

  const login = async (username: string, password: string): Promise<LoginResponse> => {
    try {
      const response = await publicApiClient.post('/auth/login', { username, password });

      if (response.data && response.data.success) {
        if (!response.data.data) {
          console.error('❌ Backend Success but missing data payload:', JSON.stringify(response.data, null, 2));
          return { success: false, message: 'Sunucudan gelen yanıt eksik (data objesi yok).' };
        }

        const { token: newToken, user: userData } = response.data.data;

        if (!newToken || !userData) {
          console.error('❌ Backend Success but missing token/user:', JSON.stringify(response.data.data, null, 2));
          return { success: false, message: 'Sunucudan gelen kullanıcı verisi eksik.' };
        }

        if (!userData.favorite_business_ids) {
          userData.favorite_business_ids = [];
        }

        setToken(newToken);
        setUser(userData);
        await AsyncStorage.setItem('@authToken', newToken);
        await AsyncStorage.setItem('@authUser', JSON.stringify(userData));

        // Giriş sonrası push token backend'e kaydet
        const pushToken = await getStoredPushToken();
        if (pushToken) {
          // Token zaten var — kaydet (await etmiyoruz, giriş akışını yavaşlatmasın)
          registerPushToken(pushToken);
        }

        return { success: true };
      }

      return { success: false, message: response.data.message || 'Bilinmeyen bir hata oluştu (success: false).' };
    } catch (error) {
      const axiosError = error as AxiosError;

      if (__DEV__) {
        console.error('Login Error:', axiosError.message);
      }

      if (axiosError.response?.status === 401) {
        return { success: false, message: 'Kullanıcı adı veya şifre hatalı.' };
      }
      if (axiosError.response && axiosError.response.data) {
        const errorData = axiosError.response.data as { message?: string };
        return { success: false, message: errorData.message || 'Giriş başarısız oldu.' };
      }
      return { success: false, message: `Sunucuya bağlanılamadı. Hata: ${axiosError.message}` };
    }
  };

  // --- YER TUTUCU SOSYAL GİRİŞ FONKSİYONLARI ---
  // Backend hazır olduğunda bu fonksiyonların içi doldurulacak
  const signInWithGoogle = async (googleToken: string): Promise<LoginResponse> => {
    console.log('🟡 [AuthContext] signInWithGoogle çağrıldı');
    console.log('🟡 [AuthContext] idToken:', googleToken.substring(0, 50) + '...');

    try {
      const response = await publicApiClient.post('/auth/google', { token: googleToken });

      console.log('🟡 [AuthContext] Backend response status:', response.status);
      console.log('🟡 [AuthContext] Backend response data:', JSON.stringify(response.data, null, 2));

      if (response.data && response.data.success) {
        const { token: newToken, user: userData } = response.data.data;
        if (!userData.favorite_business_ids) {
          userData.favorite_business_ids = [];
        }
        setToken(newToken);
        setUser(userData);
        await AsyncStorage.setItem('@authToken', newToken);
        await AsyncStorage.setItem('@authUser', JSON.stringify(userData));
        console.log('🟢 [AuthContext] Token ve user kaydedildi');
        const needsSetup = response.data.data.needs_username_setup === true || isAutoGeneratedUsername(userData.username);
        setNeedsUsernameSetup(needsSetup);

        // Google giriş sonrası push token kaydet
        const pushToken = await getStoredPushToken();
        if (pushToken) {
          registerPushToken(pushToken);
        }

        return { success: true, needsUsernameSetup: needsSetup };
      }
      console.log('🔴 [AuthContext] Backend\'den token veya user gelmedi');
      return { success: false, message: response.data.message || 'Google ile giriş başarısız oldu.' };
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error('🔴 [AuthContext] Google Sign-In error:', axiosError);
      console.error('🔴 [AuthContext] Error response:', axiosError.response?.data);
      console.error('🔴 [AuthContext] Error status:', axiosError.response?.status);
      return { success: false, message: axiosError.response?.data.message || 'Sunucuya bağlanılamadı veya Google ile giriş başarısız.' };
    }
  };

  const completeUsernameSetup = async (newUsername: string): Promise<{ success: boolean; message?: string }> => {
    try {
      const response = await privateApiClient.patch('/auth/username', { username: newUsername });
      if (response.data && response.data.success) {
        const updatedUser = { ...user!, username: newUsername };
        setUser(updatedUser);
        await AsyncStorage.setItem('@authUser', JSON.stringify(updatedUser));
        setNeedsUsernameSetup(false);
        return { success: true };
      }
      return { success: false, message: response.data.message || 'Kullanıcı adı kaydedilemedi.' };
    } catch (error: any) {
      const axiosError = error as AxiosError;
      if (axiosError.response?.status === 409) {
        return { success: false, message: 'Bu kullanıcı adı zaten alınmış.' };
      }
      return { success: false, message: 'Bir hata oluştu. Lütfen tekrar deneyin.' };
    }
  };

  const signInWithApple = async (appleToken: string, fullName: string | null): Promise<LoginResponse> => {
    try {
      const response = await publicApiClient.post('/auth/apple', { token: appleToken, fullName: fullName });

      if (response.data && response.data.success) {
        const { token: newToken, user: userData } = response.data.data;
        if (!userData.favorite_business_ids) {
          userData.favorite_business_ids = [];
        }
        setToken(newToken);
        setUser(userData);
        await AsyncStorage.setItem('@authToken', newToken);
        await AsyncStorage.setItem('@authUser', JSON.stringify(userData));
        const needsSetup = response.data.data.needs_username_setup === true || isAutoGeneratedUsername(userData.username);
        setNeedsUsernameSetup(needsSetup);

        // Apple giriş sonrası push token kaydet
        const pushToken = await getStoredPushToken();
        if (pushToken) {
          registerPushToken(pushToken);
        }

        return { success: true, needsUsernameSetup: needsSetup };
      }
      return { success: false, message: response.data.message || 'Apple ile giriş başarısız oldu.' };
    } catch (error) {
      const axiosError = error as AxiosError;
      console.error("Apple ile giriş hatası:", axiosError.response?.data || axiosError.message);
      return { success: false, message: axiosError.response?.data.message || 'Sunucuya bağlanılamadı veya Apple ile giriş başarısız.' };
    }
  };

  const logout = async () => {
    // Çıkış yapmadan önce push token'ı backend'den sil
    try {
      await unregisterPushToken();
    } catch {
      // Sessizce geç — çıkış akışını engelleme
    }
    setToken(null);
    setUser(null);
    setNeedsUsernameSetup(false);
    await AsyncStorage.removeItem('@authToken');
    await AsyncStorage.removeItem('@authUser');
  };

  const isFavorite = (businessId: number): boolean => {
    return user?.favorite_business_ids?.includes(businessId) ?? false;
  };

  const addFavorite = async (businessId: number) => {
    if (!user) return;

    // Önce kontrol et - zaten favorideyse ekleme
    if (user.favorite_business_ids?.includes(businessId)) {
      return;
    }

    const updatedUser = { ...user, favorite_business_ids: [...(user.favorite_business_ids || []), businessId] };
    setUser(updatedUser);

    try {
      await privateApiClient.post('/favorites', { business_id: businessId });
      await AsyncStorage.setItem('@authUser', JSON.stringify(updatedUser));
    } catch (error: any) {
      console.error("❌ Favori eklenemedi:", error);
      console.error("Response:", error.response?.data);
      // Hata durumunda geri al
      setUser(user);
      if (error.response?.status === 409) {
        alert("Bu işletme zaten favorilerinizde.");
      } else {
        alert("Favori eklenirken bir hata oluştu.");
      }
    }
  };

  const removeFavorite = async (businessId: number) => {
    if (!user) return;

    // Önce kontrol et - favoride değilse silme
    if (!user.favorite_business_ids?.includes(businessId)) {
      return;
    }

    const updatedUser = { ...user, favorite_business_ids: (user.favorite_business_ids || []).filter(id => id !== businessId) };
    setUser(updatedUser);

    try {
      await privateApiClient.delete(`/favorites/${businessId}`);
      await AsyncStorage.setItem('@authUser', JSON.stringify(updatedUser));
    } catch (error) {
      console.error("❌ Favori silinemedi:", error);
      // Hata durumunda geri al
      setUser(user);
      alert("Favori silinirken bir hata oluştu.");
    }
  };

  const refreshPuanBalance = async () => {
    if (!token) return;
    const balance = await getPuanBalance();
    setPuanBalance(balance);
  };

  // Giriş/çıkış durumu değiştiğinde puan bakiyesini güncelle
  useEffect(() => {
    if (token) {
      refreshPuanBalance();
    } else {
      setPuanBalance(0);
    }
  }, [token]);

  return (
    <AuthContext.Provider value={{
      token,
      user,
      isAuthenticated: !!token,
      isLoading,
      needsUsernameSetup,
      puanBalance,
      refreshPuanBalance,
      login,
      logout,
      setUser,
      addFavorite,
      removeFavorite,
      isFavorite,
      signInWithGoogle,
      signInWithApple,
      completeUsernameSetup,
    }}>
      {children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (context === undefined) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};